### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by clopez** [Igalia/dyz#11]
Pretty much like https://github.com/Igalia/WPEBackend-fdo/issues/2 .. please add a license file :)

**Comment by zdobersek** [comment]
https://github.com/Igalia/WPEBackend-fdo/commit/c2bdbea9eaec91e7b0dd83f9f1d9ce5b48f21f93

**Comment by zdobersek** [comment]
https://github.com/Igalia/dyz/commit/8f7c851064f1ff1f2535e49be9128b190617663b
